version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: freelanceflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - freelanceflow

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - freelanceflow

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/freelanceflow
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-this-in-production
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:80
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - freelanceflow

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - freelanceflow

volumes:
  postgres_data:

networks:
  freelanceflow:
    driver: bridge